### ISSUE TITLE
Search do not work

### ISSUE THREAD

**Issue by dmstek** [hulkrelax/deckfaqs#18]
Both custom search and search for title show no results. Show load icon and that's it.

**Comment by hulkrelax** [comment]
What version of DeckFAQs are you using? There may be an update you need to grab. Latest Steam Client broke some stuff so I had to update DeckFAQs a few days ago to fix it

**Comment by hulkrelax** [comment]
Search is working fine for me fwiw

**Comment by dmstek** [comment]
> Search is working fine for me fwiw

Does not work for me. Decky Loader 2.4.9-pre1. DeckFAQs 1.5.3. OS version 3.4.2 - 20221221.2

**Comment by hulkrelax** [comment]
Seems like it could just be a networking issue on your end. I have the same software configuration and everything works. Have you tried just going to GameFAQs using Chrome on the Deck and searching games there? It that doesn't work then it's definitely something with your network.

**Comment by dmstek** [comment]
Yes, all works in Chrome, but not in DeckFaqs, see screenshot, I just opened DeckFaqs in Chrome and searched for exact same thing there. Got infinite loader. Nothing else I tried produce any results in DeckFaqs too, always infinite loader icon.

Is there any way I can debug this and find out what happens? Maybe you can build a debug version? As definitely web works from Decky, as I downloaded DeckFaqs from the Decky store without any problem, so it looks like something is wrong with DeckFaqs communication.

Your HLTB plugin gets information from HLTB too, data is updated, link opens. Only issue is with DeckFaqs.

![image](https://user-images.githubusercontent.com/86744871/211397865-bbe11646-11ce-45e9-86cc-c9bed189a9d7.png)

**Comment by dmstek** [comment]
@hulkrelax is there any way to do a debug for your plugin? maybe log request/response or something.

**Comment by hulkrelax** [comment]
The plugin is open source, you are free to make changes and make a build yourself. It's hard for me to help you in this situation because I cannot reproduce your issue. You are also the only person reporting this issue. No one else is having issues as far as I can tell. If you had reliable reproduction steps, then maybe I could do something but at this point I'm not sure there is much I can do.

**Comment by dmstek** [comment]
> The plugin is open source, you are free to make changes and make a build yourself. It's hard for me to help you in this situation because I cannot reproduce your issue. You are also the only person reporting this issue. No one else is having issues as far as I can tell. If you had reliable reproduction steps, then maybe I could do something but at this point I'm not sure there is much I can do.

After update to Decky 2.5.0 all started magically working. Also maybe there is a relation for steam client being online or offline. In any case it works for me now, thanks.
