### ISSUE TITLE
Deckfaqs completely broken in Steam Client Beta (Feb 18)

### ISSUE THREAD

**Issue by DJScias** [hulkrelax/deckfaqs#22]
Hello there,

Figured I would be proactive and report this before this beta hits the stable channel.

This is most likely related to the investigated issues described by [Decky Loader's latest release](https://github.com/SteamDeckHomebrew/decky-loader/releases/tag/v2.5.4) ("Unfortunately, there is a more extensive issue with plugins that navigate to external web pages which we cannot fix via a Decky Loader update.").

As per them, it's still under investigation and thus might not be easily solveable just yet.

The following screenshots show what happens with DeckFaq on the latest steam client beta.
![20230218171604_1](https://user-images.githubusercontent.com/439655/219878406-dbdc3668-855f-4b55-aaac-3b51d1d005d4.jpg)
![20230218171610_1](https://user-images.githubusercontent.com/439655/219878410-a005cc1b-4d28-41bb-afde-bcb0e78a46b5.jpg)
![20230218171714_1](https://user-images.githubusercontent.com/439655/219878643-b31fc96f-a5b9-4407-a774-02252a2ecc2a.jpg)

I wish I could make the error display more, but there's no real means for me to make the window go right during its display.

**Comment by hulkrelax** [comment]
Thanks for the heads up. Not surprised a beta broke everything :). Guess I got a busy weekend

**Comment by DJScias** [comment]
Hey there.

I honestly feel for you. Although I just saw they put in a PR a bit ago https://github.com/SteamDeckHomebrew/decky-frontend-lib/pull/75 at the frontend-lib repo.

Maybe that's related to it? I haven't done any real checking yet to see if you make use of `NavigateToExternalWeb` specifically (although it'd make sense since gamefaq is an external site compared to Valve's steam deck).

**Comment by hulkrelax** [comment]
It might partially be related although that PR fixes an issue with HLTB For Deck which I have verified. DeckFAQs is in a whole other broken state. It seems Valve has just removed and/or moved functionality around so I just have to find out where it's been moved to.

**Comment by DJScias** [comment]
I'm sure you guys can crack the code, watching you all work in the Steam Deck Homebrew discord.

Once a testing variant is out, I'll see what I can do in helping with testing it @ the plugin store to get it greenlit ASAP.

Thank you again for tackling this so vigorously. 👍

**Comment by hulkrelax** [comment]
I have a PR up on decky plugin store to fix this. look out for v1.6.0 soon™

**Comment by DJScias** [comment]
Alright, I'll test it now. :)

**Comment by DJScias** [comment]
Tested in https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/242#pullrequestreview-1304855226 and it once more works just fine!

Found a minor issue, but I'll make a separate issue here for it. I'll let you close this when you want. :)
