### ISSUE TITLE
System crash searching for FAQ within MotoGP 18

### ISSUE THREAD

**Issue by mikehgentry** [hulkrelax/deckfaqs#29]
Stable Steam OS (3.4.6), stable Decky (2.6.4), Milestone's MotoGP 18 installed from the Steam store.

Upon opening Deckfaqs I am given the button to search for a FAQ for the game (labelled MotoGP 18 with a superscript TM). Hitting it the screen goes black, backlight remains on, but no buttons respond aside from long-pressing power to shut down.

It may be noteworthy that there is no FAQ on the site for this title?

**Comment by hulkrelax** [comment]
I have an update to DeckFAQs (v 1.7.0) for review on the testing store that should fix most crashes.

**Comment by mikehgentry** [comment]
Sorry, should have tested that - you are right, it works.

Thanks!
