### ISSUE TITLE
DeckFAQs seems to cause the screen to black out whenever any gamescope overlay changes in SteamOS.

### ISSUE THREAD

**Issue by sirocyl** [hulkrelax/deckfaqs#30]
Tested with latest beta and stable Steam Client version as of time of writing (20230801).
Decky Loader is prerelease; Store Channel is default. Current Decky loader is 2.10.4-pre6.

Correlate this with the bug, in particular, the comment I posted at the SteamOS repo's tracker, [here.](https://github.com/ValveSoftware/SteamOS/issues/1109#issuecomment-1661100231)

Ways to reproduce:
- Be on latest beta or stable Steam Client, I'm also on beta SteamOS.
- Have DeckFAQs installed, through the Decky Loader plugin store.
- Reboot the system, and wait for the Deck UI to load in.
- Press any volume key, or
- launch a game/app, and press the Steam button and attempt to return to the home menu.

After the volume control overlay/popup disappears, the screen will blank, and while the system will be responsive, there is no display.

Disabling DeckFAQs, and only this plugin, was sufficient to solve the errant behavior, and now launching games and using the volume controls works as intended.

I cannot be certain that other plugins don't also trigger this behavior, but something in DeckFAQs certainly does.

Willing to provide any further information, logs, and debug and run tests as needed.

**Comment by hulkrelax** [comment]
Thanks. that's a nasty one. Looks like the latest stable Steam Client busted it. Might not be trivial to fix but I'll see. For now yeah I guess just uninstall DeckFAQs

**Comment by hulkrelax** [comment]
@sirocyl This will be fixed in v1.8.0 of DeckFAQs
