### ISSUE TITLE
deckFAQs not appearing on the Decky Store

### ISSUE THREAD

**Issue by btabaska** [hulkrelax/deckfaqs#31]
#DeckFAQs is not showing up on the Decky store anymore. I am guessing it is because the decky-plugin-frontend version needs to be updated.

**Comment by hulkrelax** [comment]
No I asked for it to be taken off because latest Stable steam client gets broken by DeckFAQs

**Comment by hulkrelax** [comment]
See https://github.com/hulkrelax/deckfaqs/issues/30

**Comment by hulkrelax** [comment]
It's back on the store.
